# Generated by Django 3.1.7 on 2021-02-27 23:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('creation', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(help_text='Полное описание проекта', verbose_name='Описание проекта')),
                ('image_1', models.ImageField(default=0, help_text='Заглавная картинка проекта', upload_to='posts/')),
                ('image_2', models.ImageField(default=0, help_text='Вторая картинка проекта', upload_to='posts/')),
                ('image_3', models.ImageField(help_text='Третья картинка проекта', upload_to='posts/')),
            ],
        ),
    ]
